### ISSUE TITLE
No values in page properties

### ISSUE THREAD

**Issue by SkytAsul** [seratch/notion-sdk-jvm#73]
All the properties of pages gotten via both `NotionClient#queryDatabase` and `NotionClient#retrievePage` have no values. I cannot understand why.

Notion sdk v1.7.0 with httpclient.

**Comment by seratch** [comment]
Hi @SkytAsul, this is due to Notion API's changes in the 2022-06-28 release: https://developers.notion.com/changelog/releasing-notion-version-2022-06-28#section-page-properties-must-be-retrieved-using-the-page-properties-endpoint

If you need properties of a page, your code need to perform additional requests to fetch those.

As the maintainer of this project, I cannot help you out for this further. Let me close this issue now.

**Comment by SkytAsul** [comment]
Alright thank you. If I understood well, this means that I have to make 1 request per property?? Let's imagine I'd like to get 3 properties for like 4 pages: 12 requests! The rate limiter is going to blow up really fast...

**Comment by seratch** [comment]
@SkytAsul A good news is that they are planning to revert the painful changes soon: https://notiondevs.slack.com/archives/C01D6KN3J4A/p1661877301261269

**Comment by seratch** [comment]
The Notion platform reverted the changes. I will release a new version shortly https://github.com/seratch/notion-sdk-jvm/pull/76
