### ISSUE TITLE
Question regarding what I can do with the client.

### ISSUE THREAD

**Issue by the-Kob** [seratch/notion-sdk-jvm#74]
Where can I see what operations I can call with the NotionClient? I'm trying to develop a personal app in Java. I can't seem to find any other operations besides the "search" you have on the README, which works fine, but doesn't return the children of the database given,

Thanks in advance.

**Comment by seratch** [comment]
Hi @the-Kob, thanks for asking the question. You can find the full list of available operations in the following pages:
* https://developers.notion.com/reference/intro
* https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/seratch/notion-sdk-jvm-core/1.7.0/notion-sdk-jvm-core-1.7.0-javadoc.jar/!/notion/api/v1/NotionClient.html
* https://oss.sonatype.org/service/local/repositories/releases/archive/com/github/seratch/notion-sdk-jvm-core/1.7.0/notion-sdk-jvm-core-1.7.0-javadoc.jar/!/notion/api/v1/endpoint/package-summary.html
* https://github.com/seratch/notion-sdk-jvm/tree/main/core/src/test/kotlin/integration_tests

As of today, this SDK supports all the available endpoints to call.

Since I've answered your questions here, let me close this issue now. When you have a more specific question in the future, feel free to open a new one.
